/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class wrapper_BoardDetector */

#ifndef _Included_wrapper_BoardDetector
#define _Included_wrapper_BoardDetector
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     wrapper_BoardDetector
 * Method:    JBoardDetector
 * Signature: (Z)V
 */
JNIEXPORT void JNICALL Java_wrapper_BoardDetector_JBoardDetector
  (JNIEnv *, jobject, jboolean);

/*
 * Class:     wrapper_BoardDetector
 * Method:    Jdetect
 * Signature: (J)F
 */
JNIEXPORT jfloat JNICALL Java_wrapper_BoardDetector_Jdetect__J
  (JNIEnv *, jobject, jlong);

/*
 * Class:     wrapper_BoardDetector
 * Method:    JgetDetectedBoard
 * Signature: ()Lwrapper/Board;
 */
JNIEXPORT jobject JNICALL Java_wrapper_BoardDetector_JgetDetectedBoard
  (JNIEnv *, jobject);

/*
 * Class:     wrapper_BoardDetector
 * Method:    JgetMarkerDetector
 * Signature: ()Lwrapper/MarkerDetector;
 */
JNIEXPORT jobject JNICALL Java_wrapper_BoardDetector_JgetMarkerDetector
  (JNIEnv *, jobject);

/*
 * Class:     wrapper_BoardDetector
 * Method:    JgetDetectedMarkers
 * Signature: ()Ljava/util/ArrayList;
 */
JNIEXPORT jobject JNICALL Java_wrapper_BoardDetector_JgetDetectedMarkers
  (JNIEnv *, jobject);

/*
 * Class:     wrapper_BoardDetector
 * Method:    JsetYPerpendicular
 * Signature: (Z)V
 */
JNIEXPORT void JNICALL Java_wrapper_BoardDetector_JsetYPerpendicular
  (JNIEnv *, jobject, jboolean);

/*
 * Class:     wrapper_BoardDetector
 * Method:    Jdetect
 * Signature: (Ljava/util/ArrayList;Lwrapper/BoardConfiguration;Lwrapper/Board;Lwrapper/CameraParameters;F)F
 */
JNIEXPORT jfloat JNICALL Java_wrapper_BoardDetector_Jdetect__Ljava_util_ArrayList_2Lwrapper_BoardConfiguration_2Lwrapper_Board_2Lwrapper_CameraParameters_2F
  (JNIEnv *, jobject, jobject, jobject, jobject, jobject, jfloat);

/*
 * Class:     wrapper_BoardDetector
 * Method:    Jdetect
 * Signature: (Ljava/util/ArrayList;Lwrapper/BoardConfiguration;Lwrapper/Board;JJF)F
 */
JNIEXPORT jfloat JNICALL Java_wrapper_BoardDetector_Jdetect__Ljava_util_ArrayList_2Lwrapper_BoardConfiguration_2Lwrapper_Board_2JJF
  (JNIEnv *, jobject, jobject, jobject, jobject, jlong, jlong, jfloat);

#ifdef __cplusplus
}
#endif
#endif
