/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class wrapper_FiducidalMarkers */

#ifndef _Included_wrapper_FiducidalMarkers
#define _Included_wrapper_FiducidalMarkers
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     wrapper_FiducidalMarkers
 * Method:    JcreateMarkerImage
 * Signature: (IIJ)V
 */
JNIEXPORT void JNICALL Java_wrapper_FiducidalMarkers_JcreateMarkerImage
  (JNIEnv *, jobject, jint, jint, jlong);

/*
 * Class:     wrapper_FiducidalMarkers
 * Method:    Jdetect
 * Signature: (JI)I
 */
JNIEXPORT jint JNICALL Java_wrapper_FiducidalMarkers_Jdetect
  (JNIEnv *, jobject, jlong, jint);

/*
 * Class:     wrapper_FiducidalMarkers
 * Method:    JgetMarkerMat
 * Signature: (IJ)V
 */
JNIEXPORT void JNICALL Java_wrapper_FiducidalMarkers_JgetMarkerMat
  (JNIEnv *, jobject, jint, jlong);

/*
 * Class:     wrapper_FiducidalMarkers
 * Method:    JcreateBoardImage
 * Signature: (DDIILwrapper/BoardConfiguration;Ljava/util/ArrayList;J)V
 */
JNIEXPORT void JNICALL Java_wrapper_FiducidalMarkers_JcreateBoardImage
  (JNIEnv *, jobject, jdouble, jdouble, jint, jint, jobject, jobject, jlong);

/*
 * Class:     wrapper_FiducidalMarkers
 * Method:    JcreateBoardImage_ChessBoard
 * Signature: (DDILwrapper/BoardConfiguration;ZLjava/util/ArrayList;J)V
 */
JNIEXPORT void JNICALL Java_wrapper_FiducidalMarkers_JcreateBoardImage_1ChessBoard
  (JNIEnv *, jobject, jdouble, jdouble, jint, jobject, jboolean, jobject, jlong);

/*
 * Class:     wrapper_FiducidalMarkers
 * Method:    JcreateBoardImage_Frame
 * Signature: (DDIILwrapper/BoardConfiguration;ZLjava/util/ArrayList;J)V
 */
JNIEXPORT void JNICALL Java_wrapper_FiducidalMarkers_JcreateBoardImage_1Frame
  (JNIEnv *, jobject, jdouble, jdouble, jint, jint, jobject, jboolean, jobject, jlong);

#ifdef __cplusplus
}
#endif
#endif
